# ~/.config/starship.toml

add_newline = false
scan_timeout = 10

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]]
threshold = 90
style = "bold red"

[character]
symbol = "ğŸš€"
error_symbol = "â›”"
use_symbol_for_status = true

[cmd_duration]
min_time = 500
show_milliseconds = true

[git_commit]
commit_hash_length = 4
only_detached = false
